### ISSUE TITLE
Auto AFK Mode activates early and resets time to 3 minutes

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#28]
When Auto AFK activates, it strips most of the time - going from 30 to 3 in the last testing. It also activates very early - possibly within minutes after activation.

**Comment by emmamei** [comment]
The "early activation" was a result of invalid code testing for Away status; this has been fixed.

**Comment by silkymesmeriser** [comment]
I just ran into this one and fixed it myself too while trying to fix the math error issue I spotted it, is just a few lines above where the other issue was which was a DIV/0 in the llMessageLinked line there

**Comment by emmamei** [comment]
The new commit has reintroduced a form of this bug. If the user enters AFK mode manually, it is reset almost immediately by the automatic AFK code.

**Comment by silkymesmeriser** [comment]
This was a weird one took me a while to come with a solution that appears to work and also I think makes some sense, the other implementation had the issue also that if AFK was ever set manually if it had worked correctly it would have been stuck in manual mode permanently.

My reworked implementation works slightly differently though it might be actually what you were aiming for I still can't work out exactly why it wasn't working actually.  Anyway the autoAFK variable now functions like a derived/implied config variable by default it is true and will remain that way until the user hits Toggle AFK.

When Toggle AFK is used the setting of autoAFK is then derived from the following code:

```
    integer agentInfo = llGetAgentInfo(dollID);
    if ((agentInfo & AGENT_AWAY) && afk) autoAFK = 1;
    else if (!(agentInfo & AGENT_AWAY) && !afk) autoAFK = 1;
    else autoAFK = 0;
```

So pretty much if USER_MODE == AUTO_MODE then auto is on else it's off.

Currently it will only re enabled if it is manually toggled back to a matching mode through the key menu, I did consider having it re-enabled itself if the away mode of the viewer was reset to match that way also however it struck me that the issue with that is the viewer mode can and does by default get auto set as such this could result in the setting being switched on the user without them expecting or being aware of it.

I decided to err on the principle of least surprisal on that and only reset it when the mode is toggled using the key.

Any thoughts?

**Comment by emmamei** [comment]
Not sure I follow. The idea behind autoAFK was simple: it told the code that the current AFK status was automatically set. I dont comprehend what it means now - nor what the meaning of newAFK is either.

Automatic setting of AFK based on AGENT_AWAY isnt a toggle - but a setting and unsetting.

**Comment by silkymesmeriser** [comment]
It essentially does the same thing that I think yours was intending to but the way you had it before the code was only checking autoAFK before turning AFK mode off, if AFK mode was toggled off by the user manually while AGENT_AWAY then it would force it back on immediately now if the user toggles the AFK in the menu to a state different to what the auto code would have it as then it disables automatic transitions till manually set back.  Which to me seems to be the right way to go about it as if the user has set it differently.

Ah, newAFK is basically a trick to save memory, is the best of the time memory tradeoffs available to choose from for this purpose.  I changed the varname in the new code though to make it more obvious what it's purpose is, it's not called dollAway.

```
    integer dollAway = ((llGetAgentInfo(dollID) & AGENT_AWAY) != 0);
    if (autoAFK && afk != dollAway) {
        llMessageLinked(LINK_SET, 305, llGetScriptName() + "|setAFK|" + (string)(afk = dollAway) + "|1|" + formatFloat(setWindRate(), 1) + "|" + (string)llRound(timeLeftOnKey / (60.0 * windRate)), NULL_KEY);
    }
```

You can do the same thing using a few hundred bytes more memory using something like this:

```
    if (autoAFK && !afk && (llGetAgentInfo(dollID) * AGENT_AWAY) != 0) {
        afk = 1;
        llMessageLinked(LINK_SET, 305, llGetScriptName() + "|setAFK|" + (string)afk + "|1|" + formatFloat(windRate, 1) + "|" + (string)minsLeft, NULL_KEY);
    } else if (autoAFK && !afk && (llGetAgentInfo(dollID) * AGENT_AWAY) == 0) {
        afk = 0;
        llMessageLinked(LINK_SET, 305, llGetScriptName() + "|setAFK|" + (string)afk + "|1|" + formatFloat(windRate, 1) + "|" + (string)minsLeft, NULL_KEY);
    }
```

Or the third alternative which uses a mass of script time extra though it is a couple of bytes less memory than the current implementation:

```
    if (autoAFK && !afk && (llGetAgentInfo(dollID) * AGENT_AWAY) != 0) afk = 1;
    else if (autoAFK && !afk && (llGetAgentInfo(dollID) * AGENT_AWAY) == 0) afk = 0;
    llMessageLinked(LINK_SET, 305, llGetScriptName() + "|setAFK|" + (string)afk + "|1|" + formatFloat(windRate, 1) + "|" + (string)minsLeft, NULL_KEY);
```

The problem with the last form is that we would be waking up the link_message event of all 7 scripts every second and triggering RLV.lsl to state check a long list of restrictions which is loop cycles and would boost script time even without the other wakeups.

**Comment by emmamei** [comment]
Your second and third examples have some troubles with them. In particular, the llGetAgentInfo is called several times and might change in between - and afk can be considered a constant in the second:

```
        afk = 0;
        llMessageLinked(LINK_SET, 305, llGetScriptName() + "|setAFK|0|1|" + formatFloat(windRate, 1) + "|" + (string)minsLeft, NULL_KEY);
```

Most importantly, your code will always return 1 for the afk value:

```
(string)(afk = dollAway)
```

This will always be a TRUE value as long as afk is assigned a value. I think you meant:

```
 integer dollAway = ((llGetAgentInfo(dollID) & AGENT_AWAY) != 0);
    if (autoAFK && afk != dollAway) {
        afk = dollAway;
        llMessageLinked(LINK_SET, 305, llGetScriptName() + "|setAFK|" + (string)(afk) + "|1|" + formatFloat(setWindRate(), 1) + "|" + (string)llRound(timeLeftOnKey / (60.0 * windRate)), NULL_KEY);
    }
```

Your example code also doesn't take into effect that the doll might not be winding down, and might have a windRate of 0.0.

**Comment by emmamei** [comment]
Looked at the code in the repository and tried to understand it - and got this:

```
        integer agentInfo = llGetAgentInfo(dollID);
        integer newAFK;

        // When Dolly is "away" - enter AFK
        if (agentInfo & AGENT_AWAY) {
            newAFK = 1;
            autoAFK = 1;
        } else
            // Dolly is not AWAY
            //
            // The conditional is the following:
            //   1. Dolly is neither afk nor previously AWAY (0 && 0)
            //   2. Dolly is AFK and was previously AWAY (1 && 1)
            if (afk && autoAFK) {
                newAFK = 0;
                autoAFK = 0;
            }

        setWindRate();

        // This will only happen in these cases:
        //   1. The Dolly is NOT AFK but goes into AWAY state (1 != 0)
        //   2. The Dolly is AFK but comes out of AWAY state (0 != 1)
        //
        // After this statement runs, it will not run again until newAFK or afk changes.
        //
        if (newAFK != afk) {
            integer minsLeft;
            if (windRate > 0.0) minsLeft = llRound(timeLeftOnKey / (60.0 * windRate));
            afk = newAFK;
            llMessageLinked(LINK_SET, 305, llGetScriptName() + "|setAFK|" + (string)(afk) +
                                                               "|" + (string)autoAFK +
                                                               "|" + formatFloat(windRate, 1) +
                                                               "|" + (string)minsLeft, NULL_KEY);
        }
```

Seems to me that newAFK is not a "trick" but rather it marks the transition into and out of an automatic AFK. One consideration this misses: what if the user is afk when they enter AWAY status?

**Comment by silkymesmeriser** [comment]
That should be fixed with the new implementation
